### ISSUE TITLE
No Issue, Question (Home Assistant)

### ISSUE THREAD

**Issue by haus51** [mensi/ekzexport#2]
hi mensi, zwei fragen..

1. weisst du, ob man neben dem 15-min-verbrauch auch andere daten direkt auslesen kann, z.b. total von tag/monat/jahr?

gibt es für den link andere typen neben PK_VERB_15MIN?

https://my.ekz.ch/api/portal-services/consumption-view/v1/consumption-data?installationId=XXXXXX&from=2024-06-12&to=2024-06-12&type=PK_VERB_15MIN

2. gerne würde ich in home assistant die daten von my.ekz auslesen. knackpunkt ist wohl das notwendige login.
kann man deine variante in hass nutzen, z.b. mit pyscript integration? oder kennst du eine andere möglicheit?

vielen dank und liebe grüsse

**Comment by mensi** [comment]
1. Ja, kannst du mit dem CLI command "properties" auslesen (siehe README.md). Ich glaube `VERB_TAG_EDM` waren die Tageswerte. Gröber als Tag gibt's soweit ich weiss nicht, da musst du aufsummieren.

2. Bei Home Assistant bin ich mir nicht so sicher... Ich habe mir das mit den Energiedaten mal angeschaut, und man könnte via MQTT + Autodiscovery was machen. Das Problem ist halt, dass das EKZ die Daten nur ein paar mal täglich updated, das bringt dann nicht viel, einfach 12 Stunden Daten auf sofort via MQTT an Home Assistant zu schieben. Ich glaube die meisten benutzen da irgend einen Shelly irgendwas Stromzähler am Sicherungskasten für die Liveverbrauchsdaten.

**Comment by haus51** [comment]
1. funktioniert. schade gibts die monatswerte nicht.

2. die livedaten brauche ich gar nicht über diesen weg, der live verbrauch wird durch plugs bedient (ecoflow BKW).
ich möchte nur die fertigen tageswerte (jeweils gestern) auslesen für die aktuelle statistik übersicht. aktuell lasse ich mit power automate die werte von my.ekz.ch scrapen, in csv speichern und in excel übertragen.
probleme dabei: pc muss laufen und scrape manuell auslösen, und vor allem, die reguläre ekz übersicht hinkt immer zwei tage hinterher. im gegensatz zur API abfrage, da bekomme ich ja die werte bis gestern und je nach tageszeit sogar die unfertigen werte von heute.
daher mein gedanke, dass es doch möglich sein muss, mit einem python script in home assistant die API abfrage automatisch ausführen zu lassen. dein exporter macht das ja, einfach nicht für home assistant konstruiert.
ich nutze in hass aktuell python scripts inkl. login daten, um befehle an ecoflow geräte zu senden. aber diese scripts waren vorgefertigt und ich musste nur meine gerätdaten einfügen. leider habe ich zu wenig ahnung, um selber ein script ausführlicher (um)zuschreiben.
kann mir vorstellen, das man vieles aus deinem exporter nutzen könnte?

**Comment by mensi** [comment]
Es kann sein, dass ich da was falsch verstanden habe, aber bei Home Assistant sind doch all diese Integrationen bei https://www.home-assistant.io/docs/energy/electricity-grid/ immer Sensoren, die Momentanwerte auslesen. Ich weiss nicht so ganz, wie das dann mit dem EKZ Portal Sinn machen soll, da dieses ja nur verzögert und gebündelte Daten liefert. 

Was ich bei mir mache ist, dass ich die Daten in eine InfluxDB schiebe und dann mit Grafana visualisiere. Da kommt es ja nicht draufan, wie verzögert die Daten ankommen - die neusten Werte fehlen halt einfach auf dem Dashboard.

**Comment by haus51** [comment]
also meinen landis smart meter kann ich nicht direkt auslesen, weil der im untergeschoss vom mietshaus hängt, bekomme ich keine wifi verbindung in meine wohnung. daher ist my.ekz meine mögliche quelle.
es reicht mir der gebündelte wert von jeweils gestern. 

home assistant ist grundätzlich meine platform, wo ich auch ein python script laufen lassen kann, habe nichts mit linux oder so eingerichtet.
darum müsste ich die scripts bzw. deinen exporter in home assistant laufen lassen können. die frage ist, wie ich das einrichte. ha kann ja grundsätzlich python.
mir reicht der wert in einer csv datei, damit kann ich weiterarbeiten.

**Comment by mensi** [comment]
Also wenn einfach das CSV update reicht, kannst du ja ekzexport von PyPI installieren lassen (laut https://community.home-assistant.io/t/where-is-python-and-how-do-i-run-pip-or-imports/516276/3 sollte das mit `python_packages:` in der Konfiguration gehen) und dann mit https://www.home-assistant.io/integrations/shell_command/ ausführen?

Ich habe Home Assistant halt als Container in meinem normalen Linux Homeserver installiert, da lasse ich das einfach direkt laufen ohne via Home Assistant zu gehen. Daher keine Ahnung wie man das am besten integriert.

**Comment by haus51** [comment]
vielen dank für deine inputs, werde ich ausprobieren.
